@extends('layouts.app')

@section('content')
<div class="container">
    <h1>Create Sales Report</h1>
    <form action="{{ route('sales_reports.store') }}" method="POST">
        @csrf
        <div class="mb-3">
            <label for="date_generated" class="form-label">Date Generated</label>
            <input type="date" class="form-control" id="date_generated" name="date_generated" required>
        </div>
        <div class="mb-3">
            <label for="total_sales" class="form-label">Total Sales</label>
            <input type="number" step="0.01" class="form-control" id="total_sales" name="total_sales" required>
        </div>
        <div class="mb-3">
            <label for="total_expenses" class="form-label">Total Expenses</label>
            <input type="number" step="0.01" class="form-control" id="total_expenses" name="total_expenses" required>
        </div>
        <div class="mb-3">
            <label for="net_profit" class="form-label">Net Profit</label>
            <input type="number" step="0.01" class="form-control" id="net_profit" name="net_profit" required>
        </div>
        <div class="mb-3">
            <label for="report_type" class="form-label">Report Type</label>
            <select class="form-control" id="report_type" name="report_type" required>
                <option value="daily">Daily</option>
                <option value="weekly">Weekly</option>
                <option value="monthly">Monthly</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="generated_by" class="form-label">Generated By</label>
            <input type="number" class="form-control" id="generated_by" name="generated_by" required>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>
@endsection
