@extends('layouts.app')

@section('content')
<div class="container">
    <h1>Sales Report #{{ $salesReport->report_id }}</h1>
    <table class="table">
        <tr>
            <th>Date Generated:</th>
            <td>{{ $salesReport->date_generated }}</td>
        </tr>
        <tr>
            <th>Total Sales:</th>
            <td>₱{{ number_format($salesReport->total_sales, 2) }}</td>
        </tr>
        <tr>
            <th>Total Expenses:</th>
            <td>₱{{ number_format($salesReport->total_expenses, 2) }}</td>
        </tr>
        <tr>
            <th>Net Profit:</th>
            <td>₱{{ number_format($salesReport->net_profit, 2) }}</td>
        </tr>
        <tr>
            <th>Report Type:</th>
            <td>{{ ucfirst($salesReport->report_type) }}</td>
        </tr>
        <tr>
            <th>Generated By:</th>
            <td>{{ $salesReport->user->name }}</td>
        </tr>
    </table>
    <a href="{{ route('sales_reports.edit', $salesReport->report_id) }}" class="btn btn-warning">Edit</a>
    <form action="{{ route('sales_reports.destroy', $salesReport->report_id) }}" method="POST" style="display:inline;">
        @csrf
        @method('DELETE')
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
</div>
@endsection
